# Generated by Django 5.1 on 2024-09-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='drink1',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='drink2',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='status',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='todo1',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='todo2',
        ),
    ]
