# Generated by Django 5.1 on 2024-09-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_settings_drink1_remove_settings_drink2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='drink1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settings',
            name='drink2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='settings',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='todo1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='todo2',
            field=models.BooleanField(default=False),
        ),
    ]
