# Generated by Django 5.1 on 2024-09-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_settings_drink1_settings_drink2_settings_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='status2',
            field=models.BooleanField(default=False),
        ),
    ]
