# Generated by Django 5.1 on 2024-09-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_settings_status2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='status2',
        ),
    ]
